# Generated by Django 2.1.3 on 2018-11-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_auto_20181107_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='add_date',
            field=models.DateField(auto_now_add=True, verbose_name='Add date'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='gender',
            field=models.CharField(max_length=30, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='talents',
            field=models.CharField(max_length=100, verbose_name='Talents'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.FloatField(verbose_name='Weight'),
        ),
    ]
