# Generated by Django 2.1.3 on 2018-11-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_auto_20181113_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='Photo'),
        ),
    ]
