# Generated by Django 2.1.2 on 2018-11-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0013_auto_20181115_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(upload_to='images', verbose_name='Photo'),
        ),
    ]
