# Generated by Django 2.1.3 on 2018-11-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0016_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
