# Generated by Django 2.1.3 on 2018-11-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0019_auto_20181122_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
