# Generated by Django 2.1.3 on 2018-12-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0020_auto_20181126_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='add_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='gender',
            field=models.CharField(max_length=30, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='talents',
            field=models.CharField(max_length=100, verbose_name='Таланты'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
    ]
